In [1]:
from incidencia_delictiva.config import PROJ_ROOT, PROCESSED_DATA_DIR

In [2]:
for item in PROCESSED_DATA_DIR.rglob("*.parquet"): 
    print(item.relative_to(PROJ_ROOT))

data/processed/marginacion/marginacion.parquet
data/processed/pobreza/pobreza.parquet
data/processed/geo/geodata.parquet
data/processed/delitos/delitos.parquet

Definimos las rutas:

In [3]:
marginacion_path = PROCESSED_DATA_DIR / "marginacion/marginacion.parquet"
pobreza_path = PROCESSED_DATA_DIR / "pobreza/pobreza.parquet"
geodata_path = PROCESSED_DATA_DIR / "geo/geodata.parquet"
delitos_path = PROCESSED_DATA_DIR / "delitos/delitos.parquet"

Los dataframes:

In [4]:
import pandas as pd

In [5]:
marginacion = pd.read_parquet(marginacion_path)
pobreza = pd.read_parquet(pobreza_path)
geodata = pd.read_parquet(geodata_path)
delitos = pd.read_parquet(delitos_path)

In [6]:
marginacion.head()

,cve_ent,nom_ent,cve_mun,nom_mun,pob_tot,analf,sbasc,ovsde,ovsee,ovsae,ovpt,vhac,pl.5000,po2sm,im_2020,gm_2020,imn_2020,cvegeo
0,1,Aguascalientes,1001,Aguascalientes,948990,1.644738,20.367220,0.104799,0.113169,0.378610,0.591434,10.339530,7.523683,54.226594,60.318795,Muy bajo,0.944508,011001
1,1,Aguascalientes,1002,Asientos,51536,3.526405,33.906364,2.650373,0.486448,0.858160,1.352430,22.942305,78.221049,78.565471,56.546071,Muy bajo,0.885433,011002
2,1,Aguascalientes,1003,Calvillo,58250,4.491509,42.482450,0.365177,0.516760,0.800978,1.040411,19.219858,51.301288,79.259777,57.058251,Muy bajo,0.893453,011003
3,1,Aguascalientes,1004,CosÃ­o,17000,3.144867,27.696745,0.712855,0.577354,0.659833,1.030989,22.716866,65.470588,81.726369,57.114030,Muy bajo,0.894326,011004
4,1,Aguascalientes,1005,JesÃºs MarÃ­a,129929,2.380588,26.692477,0.277034,0.354957,0.860426,1.312652,16.404575,37.164143,56.748753,59.011762,Muy bajo,0.924042,011005

In [7]:
marginacion.info()

<class 'pandas.DataFrame'>
RangeIndex: 2469 entries, 0 to 2468
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   cve_ent   2469 non-null   int64
 1   nom_ent   2469 non-null   str
 2   cve_mun   2469 non-null   int64
 3   nom_mun   2469 non-null   str
 4   pob_tot   2469 non-null   int64
 5   analf     2469 non-null   float64
 6   sbasc     2469 non-null   float64
 7   ovsde     2469 non-null   float64
 8   ovsee     2469 non-null   float64
 9   ovsae     2469 non-null   float64
 10  ovpt      2469 non-null   float64
 11  vhac      2469 non-null   float64
 12  pl.5000   2469 non-null   float64
 13  po2sm     2469 non-null   float64
 14  im_2020   2469 non-null   float64
 15  gm_2020   2469 non-null   str
 16  imn_2020  2469 non-null   float64
 17  cvegeo    2469 non-null   str
dtypes: float64(11), int64(3), str(4)
memory usage: 433.5 KB

In [8]:
pobreza.head()

,clave_entidad,entidad_federativa,clave_municipio,municipio,fn_poblacion,fn_pobreza_porcentaje,fn_pobreza_poblacion,fn_pobreza_extrema_porcentaje,fn_pobreza_extrema_poblacion,fn_pobreza_moderada_porcentaje,...,fn_carencia_alimentacion_nutritiva_calidad_poblacion,fn_al_menos_una_carencia_porcentaje,fn_al_menos_una_carencia_poblacion,fn_al_menos_tres_carencias_porcentaje,fn_al_menos_tres_carencias_poblacion,fn_ingreso_inferior_a_lpi_porcentaje,fn_ingreso_inferior_a_lpi_poblacion,fn_ingreso_inferior_a_lpei_porcentaje,fn_ingreso_inferior_a_lpei_poblacion,cvegeo
0,1,Aguascalientes,1001,Aguascalientes,922268.0,23.7,218414.0,2.0,18206.0,21.7,...,145444.0,51.6,475558.0,7.2,66231.0,33.7,310444.0,9.0,82866.0,011001
1,1,Aguascalientes,1002,Asientos,48635.0,40.1,19518.0,4.1,2015.0,36.0,...,13870.0,79.7,38761.0,15.7,7650.0,46.8,22737.0,15.8,7683.0,011002
2,1,Aguascalientes,1003,Calvillo,52377.0,45.8,23966.0,4.5,2356.0,41.3,...,10552.0,86.2,45164.0,14.4,7520.0,49.5,25935.0,16.0,8380.0,011003
3,1,Aguascalientes,1004,Cosío,15942.0,37.0,5905.0,3.4,538.0,33.7,...,3980.0,69.3,11043.0,10.9,1736.0,47.0,7488.0,16.5,2634.0,011004
4,1,Aguascalientes,1005,Jesús María,127962.0,26.3,33708.0,3.3,4204.0,23.1,...,22945.0,59.3,75894.0,11.0,14069.0,34.0,43565.0,10.9,13912.0,011005

In [9]:
pobreza.info()

<class 'pandas.DataFrame'>
RangeIndex: 2469 entries, 0 to 2468
Data columns (total 38 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   clave_entidad                                          2469 non-null   int64
 1   entidad_federativa                                     2469 non-null   str
 2   clave_municipio                                        2469 non-null   int64
 3   municipio                                              2469 non-null   str
 4   fn_poblacion                                           2466 non-null   float64
 5   fn_pobreza_porcentaje                                  2466 non-null   float64
 6   fn_pobreza_poblacion                                   2466 non-null   float64
 7   fn_pobreza_extrema_porcentaje                          2466 non-null   float64
 8   fn_pobreza_extrema_poblacion                           2466 non-null   float64
 9   fn_pobreza_moderada_porcentaje                         2466 non-null   float64
 10  fn_pobreza_moderada_poblacion                          2466 non-null   float64
 11  fn_vulnerable_carencias_sociales_porcentaje            2466 non-null   float64
 12  fn_vulnerable_carencias_sociales_poblacion             2466 non-null   float64
 13  fn_vulnerable_ingresos_porcentaje                      2466 non-null   float64
 14  fn_vulnerable_ingresos_poblacion                       2466 non-null   float64
 15  fn_no_pobre_no_vulnerable_porcentaje                   2466 non-null   float64
 16  fn_no_pobre_no_vulnerable_poblacion                    2466 non-null   float64
 17  fn_carencia_rezago_educativo_porcentaje                2466 non-null   float64
 18  fn_carencia_rezago_educativo_poblacion                 2466 non-null   float64
 19  fn_carencia_servicios_de_salud_porcentaje              2466 non-null   float64
 20  fn_carencia_servicios_de_salud_poblacion               2466 non-null   float64
 21  fn_carencia_seguridad_social_porcentaje                2466 non-null   float64
 22  fn_carencia_seguridad_social_poblacion                 2466 non-null   float64
 23  fn_carencia_calidad_espacios_vivienda_porcentaje       2466 non-null   float64
 24  fn_carencia_calidad_espacios_vivienda_poblacion        2466 non-null   float64
 25  fn_carencia_servicios_basicos_vivienda_porcentaje      2466 non-null   float64
 26  fn_carencia_servicios_basicos_vivienda_poblacion       2466 non-null   float64
 27  fn_carencia_alimentacion_nutritiva_calidad_porcentaje  2466 non-null   float64
 28  fn_carencia_alimentacion_nutritiva_calidad_poblacion   2466 non-null   float64
 29  fn_al_menos_una_carencia_porcentaje                    2466 non-null   float64
 30  fn_al_menos_una_carencia_poblacion                     2466 non-null   float64
 31  fn_al_menos_tres_carencias_porcentaje                  2466 non-null   float64
 32  fn_al_menos_tres_carencias_poblacion                   2466 non-null   float64
 33  fn_ingreso_inferior_a_lpi_porcentaje                   2466 non-null   float64
 34  fn_ingreso_inferior_a_lpi_poblacion                    2466 non-null   float64
 35  fn_ingreso_inferior_a_lpei_porcentaje                  2466 non-null   float64
 36  fn_ingreso_inferior_a_lpei_poblacion                   2466 non-null   float64
 37  cvegeo                                                 2469 non-null   str
dtypes: float64(33), int64(2), str(3)
memory usage: 807.8 KB

In [11]:
geodata.head()

,cvegeo,cve_ent,cve_mun,nomgeo,nom_ent,cov_,cov_id,area,perimeter,geometry,region,zona_metropolitana,zona_metropolitana_nombre,es_frontera,area_km2
0,01008,01,008,San JosÃ© de Gracia,Aguascalientes,0,1,85779.057424,181537.599566,b'\x01\x03\x00\x00\x00\x01\x00\x00\x001\x03\x0...,centro-norte,0,Unknown,0,857.790574
1,01009,01,009,TepezalÃ¡,Aguascalientes,1,2,22966.101228,89329.531705,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00S\x03\x0...,centro-norte,0,Unknown,0,229.661012
2,01010,01,010,El Llano,Aguascalientes,2,3,50405.098875,144866.490025,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\xc7\x02...,centro-norte,0,Unknown,0,504.050989
3,01011,01,011,San Francisco de los Romo,Aguascalientes,3,4,13777.017628,103689.065527,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\\\x04\x...,centro-norte,0,Unknown,0,137.770176
4,01001,01,001,Aguascalientes,Aguascalientes,4,5,116635.924756,256631.025245,b'\x01\x03\x00\x00\x00\x01\x00\x00\x00\xa2\x06...,centro-norte,1,tijuana,0,1166.359248

In [12]:
geodata.info()

<class 'pandas.DataFrame'>
RangeIndex: 2475 entries, 0 to 2474
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   cvegeo                     2475 non-null   str
 1   cve_ent                    2475 non-null   str
 2   cve_mun                    2475 non-null   str
 3   nomgeo                     2475 non-null   str
 4   nom_ent                    2475 non-null   str
 5   cov_                       2475 non-null   int64
 6   cov_id                     2475 non-null   int64
 7   area                       2475 non-null   float64
 8   perimeter                  2475 non-null   float64
 9   geometry                   2475 non-null   object
 10  region                     2475 non-null   str
 11  zona_metropolitana         2475 non-null   int64
 12  zona_metropolitana_nombre  2475 non-null   str
 13  es_frontera                2475 non-null   int64
 14  area_km2                   2475 non-null   float64
dtypes: float64(3), int64(4), object(1), str(7)
memory usage: 409.7+ KB

In [13]:
delitos.head()

,año,clave_ent,entidad,cve._municipio,municipio,bien_jurídico_afectado,tipo_de_delito,subtipo_de_delito,modalidad,enero,...,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre,cvegeo
0,2015,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,2,...,1,0,1,1,0,2,1,0,1,011001
1,2015,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,...,0,0,1,0,1,0,0,0,0,011001
2,2015,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,...,1,3,2,0,1,2,0,0,0,011001
3,2015,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,1,...,1,0,0,0,0,0,0,0,0,011001
4,2015,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,...,0,1,0,0,0,0,0,0,0,011001

In [14]:
delitos.info()

<class 'pandas.DataFrame'>
RangeIndex: 2562994 entries, 0 to 2562993
Data columns (total 22 columns):
 #   Column                  Dtype
---  ------                  -----
 0   año                     int64
 1   clave_ent               int64
 2   entidad                 str
 3   cve._municipio          int64
 4   municipio               str
 5   bien_jurídico_afectado  str
 6   tipo_de_delito          str
 7   subtipo_de_delito       str
 8   modalidad               str
 9   enero                   int64
 10  febrero                 int64
 11  marzo                   int64
 12  abril                   int64
 13  mayo                    int64
 14  junio                   int64
 15  julio                   int64
 16  agosto                  int64
 17  septiembre              int64
 18  octubre                 int64
 19  noviembre               int64
 20  diciembre               int64
 21  cvegeo                  str
dtypes: int64(15), str(7)
memory usage: 701.9 MB